taskmaster/main/urls.py
from django.contrib import admin
from django.urls import path, re_path

from tasks import views
from tasks.views import TaskListCreateView, TaskRetrieveView

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("tareas/alta/", views.create_task),
    path("tareas/editar/<int:pk>/", views.edit_task, name="edit_task"),
    path("tareas/", views.list_tasks),
    path("lab/", views.lab_view),
    path("tareas/calendar/<int:year>/", views.list_tasks_per_year),
    path("search/", views.search),
    re_path(r"^tareas/([nhl])/$", views.list_by_priority),
    re_path(r"^tareas/(normal|high|low)/$", views.list_by_priority),
    path("temas/", views.list_subjects),
    path("temas/<int:pk>/", views.subject_detail),
    path("admin/", admin.site.urls),
    path("api/tasks/", TaskListCreateView.as_view(), name="task-list-create"),
    path("api/tasks/<int:pk>/", TaskRetrieveView.as_view(), name="task-retrieve"),
]

taskmaster/tasks/urls.py
from django.urls import path

from .views import TaskListCreateView, TaskRetrieveView

urlpatterns = [
    # Otras rutas existentes...
    path("api/tasks/", TaskListCreateView.as_view(), name="task-list-create"),
    path("api/tasks/<int:pk>/", TaskRetrieveView.as_view(), name="task-retrieve"),
]

taskmaster/tasks/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone

PRIORITIES = [
    ("L", "Prioridad baja"),
    ("N", "Prioridad normal"),
    ("H", "Prioridad alta"),
]


def date_in_future(value):
    if value:
        if value < timezone.now().date():
            raise ValidationError("La fecha de entrega debe ser en el futuro")


class Subject(models.Model):
    class Meta:
        verbose_name = "Asignatura"
        verbose_name_plural = "Asignaturas"

    id = models.AutoField(primary_key=True)
    name = models.CharField(
        verbose_name="Nombre de la asignatura",
        max_length=120,
        unique=True,
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    class Meta:
        verbose_name = "Tarea"
        verbose_name_plural = "Tareas"

    # id = models.AutoField(primary_key=True) Se crea automaticamnte
    title = models.CharField(
        verbose_name="título",
        max_length=250,
        unique=True,
    )
    subject = models.ForeignKey(
        Subject,
        verbose_name="Asignatura",
        on_delete=models.PROTECT,
        related_name="tasks",
        default=1,
    )
    due_date = models.DateField(
        "Fecha de entrega",
        null=True,
        blank=True,
        default=None,
        validators=[
            date_in_future,
        ],
    )
    urgent = models.BooleanField(
        "Urgente",
        default=False,
    )
    priority = models.CharField(
        "Prioridad",
        max_length=1,
        choices=PRIORITIES,
        default="N",
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Tarea #{self.pk}: {self.title}"

taskmaster/tasks/forms.py
from django import forms

from tasks.models import Task

PRIORITIES = [
    ("L", "Prioridad baja"),
    ("N", "Prioridad normal"),
    ("H", "Prioridad alta"),
]


class SearchForm(forms.Form):
    query = forms.CharField(label="Buscar")
    priority = forms.MultipleChoiceField(
        label="Prioridad",
        required=False,
        widget=forms.CheckboxSelectMultiple,
        choices=PRIORITIES,
    )
    urgent = forms.BooleanField(
        required=False,
        label="Urgente",
    )


class CreateTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["title", "subject", "due_date", "priority", "urgent"]


class EditTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["title", "subject", "due_date", "priority", "urgent"]

taskmaster/tasks/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404
from django.shortcuts import redirect, render
from rest_framework import generics, status
from rest_framework.exceptions import NotFound
from rest_framework.generics import RetrieveAPIView
from rest_framework.response import Response

from tasks import forms
from tasks.models import Subject, Task

from .models import Task
from .serializers import TaskSerializer


def homepage(request):
    tasks = Task.objects.all().order_by("-created")[0:4]
    return render(
        request,
        "tasks/homepage.html",
        {
            "title": "TaskMaster homepage",
            "tasks": tasks,
        },
    )


LISTA_TAREAS = [
    {"id": 1, "title": "Aprender Python", "urgent": True},
    {"id": 2, "title": "Aprender Django", "urgent": True},
    {"id": 3, "title": "Comprar melocotones", "urgent": False},
]


def list_tasks(request):
    tasks = Task.objects.all()
    return render(
        request,
        "tasks/list_tasks.html",
        {
            "title": "Tareas activas",
            "tasks": tasks,
        },
    )


def list_subjects(request):
    subjects = Subject.objects.all()
    return render(
        request,
        "tasks/list_subjects.html",
        {
            "title": "Temas",
            "subjects": subjects,
        },
    )


def subject_detail(request, pk):
    subject = Subject.objects.get(pk=pk)

    return render(
        request,
        "tasks/subject_detail.html",
        {
            "title": f"Tema {subject.name}",
            "subject": subject,
        },
    )


def search(request):
    tasks = []
    query = ""
    if request.method == "POST":
        form = forms.SearchForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data["query"]
            tasks = Task.objects.filter(title__icontains=query)
            priority = form.cleaned_data.get("priority") or []
            if priority:
                tasks = tasks.filter(priority__in=priority)
            urgent = form.cleaned_data.get("urgent", False)
            if urgent:
                tasks = tasks.filter(urgent=True)
    else:
        form = forms.SearchForm()

    return render(
        request,
        "tasks/search.html",
        {
            "title": "Buscar tareas",
            "form": form,
            "tasks": tasks,
            "query": query,
        },
    )


def list_tasks_per_year(request, year):
    tasks = Task.objects.filter(created__year=year)
    return render(
        request,
        "tasks/list_tasks.html",
        {
            "title": f"Tareas creadas en el año {year}",
            "tasks": tasks,
        },
    )


def lab_view(request):
    return render(request, "tasks/lab.html", {"title": "Labs page,"})


def list_by_priority(request, priority):
    priority = priority[0].upper()
    tasks = Task.objects.filter(priority=priority)
    return render(
        request,
        "tasks/list_tasks.html",
        {
            "title": f"Tareas de prioridad {priority}",
            "tasks": tasks,
        },
    )


def create_task(request):
    if request.method == "POST":
        form = forms.CreateTaskForm(request.POST)
        if form.is_valid():
            new_task = form.save()
            return redirect("/")
    else:
        form = forms.CreateTaskForm()
    return render(
        request,
        "tasks/create_task.html",
        {
            "title": "Nueva Tarea",
            "form": form,
        },
    )


def edit_task(request, pk):
    task = Task.objects.get(pk=pk)
    if request.method == "POST":
        form = forms.EditTaskForm(request.POST, instance=task)
        if form.is_valid():
            task = form.save()
            return redirect("/")
    else:
        form = forms.EditTaskForm(instance=task)
    return render(
        request,
        "tasks/edit_task.html",
        {
            "title": f"Editar tarea #{task.pk}",
            "form": form,
        },
    )


class TaskListCreateView(generics.ListCreateAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        self.perform_create(serializer)
        task_id = serializer.instance.id

        response_data = {
            "status": {
                "type": "ok",
                "code": status.HTTP_200_OK,
                "message": "Task created successfully",
            },
            "id": task_id,
        }

        headers = self.get_success_headers(serializer.data)
        return Response(response_data, status=status.HTTP_201_CREATED, headers=headers)


class TaskRetrieveView(RetrieveAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer
    lookup_field = "pk"

    def get(self, request, *args, **kwargs):
        try:
            instance = self.get_object()
            serializer = self.get_serializer(instance)
            return Response(serializer.data)
        except Http404:
            response_data = {
                "status": {
                    "type": "error",
                    "code": 404,
                    "message": "The requested task could not be found",
                }
            }
            return Response(response_data, status=status.HTTP_404_NOT_FOUND)

taskmaster/tasks/templates/tasks/base.html
{% load static %}<html>

<head>
    <title> {{ title }} </title>
    <link rel="stylesheet" href="{% static 'tasks/css/bulma.css' %}">
    <link rel="stylesheet" href="{% static 'tasks/css/custom.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css"
        integrity="sha512-q3eWabyZPc1XTCmF+8/LuE1ozpg5xxn7iO89yfSOd5/oKvyqLngoNGsx8jq92Y8eXJ/IRxQbEC+FGSYxtk2oiw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>

    {% include 'tasks/navbar.html' %}

    <h1 class="title">TaskMaster</h1>
    <h2 class="subtitle">{{ title }}</h2>


    {% block content %}

    {% endblock content %}

    <p id="trademark"> Copyright TaskMaster 2024</p>

    {% block javascript %}

    {% endblock javascript %}

</body>

</html>

taskmaster/tasks/templates/tasks/base_y_pruebas.html
{% load static %}
<html>

<head>
    <title> {{ title }} </title>

    <link rel="stylesheet" type='text/css' href="{% static 'tasks/custom.css' %}">

</head>

<body>
    <h1 class="titulo">TaskMaster</h1>
    <h2 class="subtitulo"> {{ title }} </h2>
    <h2> No soy un subtitulo </h2>
    <p class="subtitulo"> Yo sí soy un "subtítulo" </p>

    <p> {% lorem 1 p %} </p>
    <div class="fuera">
        contefuera
        <p class="dentro">
            contenido
        </p>
    </div>


    <section class="news">
        <p>Ultimas noticias </p>
        <div>
            <p>Otro parrafo</p>
        </div>
    </section>

    <div>
        <button> Activado </button>
        <button disabled> Desactivado </button>
        <a href="https://python.org">Python</a>
        <a href="https://github.com">Github</a>
    </div>

    <ul>
        <li>one</li>
        <li>two</li>
        <li>three</li>
    </ul>

    {% block content %}

    {% endblock content %}
    <p id="trademark">CopyRight TaskMaster 2024</p>
</body>

</html>

taskmaster/tasks/templates/tasks/create_task.html
{% extends 'tasks/base.html' %}

{% block content %}
<form action="." method="POST">
    {% csrf_token %}

    <table class="table">

        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <button type="submit" value="ok">Buscar</button>
            </td>
        </tr>
    </table>
</form>
{% endblock content %}

taskmaster/tasks/templates/tasks/edit_task.html
{% extends 'tasks/base.html' %}

{% block content %}
<form action="." method="POST">
    {% csrf_token %}

    <table class="table">

        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <button type="submit" value="ok">Modificar tarea</button>
            </td>
        </tr>
    </table>
</form>
{% endblock content %}

taskmaster/tasks/templates/tasks/homepage.html
{% extends 'tasks/base.html' %}

{% block content %}

<h2>Bienvenido a TaskMaster</h2>
<h3>Lista de tareas añadidas recientemente</h3>
{% include 'tasks/task_table.html' %}

{% endblock content %}

taskmaster/tasks/templates/tasks/lab.html
{% extends 'tasks/base.html' %}
{% load static %}
{% block content %}
<hr>
<form action="'">

    <p>input (type="text" )
        <input type="text" name="username">
    </p>

    <p>input (type=password)
        <input type="password" name="password">
    </p>

    <p>input (type=cheackbox)
        <input type="checkbox" name="checkcbox">
    </p>

    <p>input (type=radio)
        <input type="radio" name="radio">
    </p>

    <p>input (type=file)
        <input type="file" name="file">
    </p>

    <p>input (type=hidden)
        <input type="hidden" name="secreto" value="xxx">
    </p>

    <p>input (type=image)
        <input type="image" name="matraka" src="{% static 'tasks/img/login-button.png' %}">
    </p>

    <p>input (type=submit)
        <input type="submit" name="GO">
    </p>

    <h2> Html 5 </h2>



    <p>input (type=color)
        <input type="color" name="color">
    </p>

    <p>input (type=date)
        <input type="date" name="date">
    </p>

    <p>input (type=datetime-local)
        <input type="datetime-local" name="datetime">
    </p>

    <p>input (type=email)
        <input type="email" name="email">
    </p>

    <p>input (type=url)
        <input /* required*/ type="url" name="url">
    </p>

    <p>input (type=tel)
        <input /* required*/ type="tel" pattern="\d\d\d \d\d\d\d" name="telefono">
    </p>

    <p>input (type=month)
        <input type="month" name="mes">
    </p>

    <p>input (type=number)
        <input type="number" name="numero">
    </p>

    <p>input (type=range)
        <input type="range" min="0" id="slider" step="10" max="100" name="rango">
    </p>
    <p>Value: <output id="value"></output></p>

    <p>input (type=search)
        <input type="search" name="query">
    </p>

    <h2 class="is-size-2" TextArea></h2>

    <fieldset>
        <legend>Descripción del subformulario</legend>


        <textarea name="texto" cols="80" rows="7" minlength="10" maxlength="2048">
        Escribe tu problema

    </textarea>

        <p>
            <label for="cb-ninja">Seleccion tu tortuga ninja / artista famoso del renacimiento italiano:
                <select name="ninja" id="cb-ninja">
                    <option value="leo">Leonardo</option>
                    <option value="mike">Michelangelo</option>
                    <option value="don">Donatello</option>
                    <option value="ralph" selected>Raphael</option>
                </select>
            </label>
        </p>
    </fieldset>


</form>

{% endblock content %}

{% block javascript %}
<script>
    console.log('Funciona!')

    const value = document.querySelector('#value');
    const input = document.querySelector('#slider');

    value.textContent = input.value;
    input.addEventListener("input", (event) => {
        value.textContent = event.target.value
    });
</script>
{% endblock javascript %}

taskmaster/tasks/templates/tasks/list_subjects.html
{% extends 'tasks/base.html' %}

{% block content %}

<div id="subjects">
    <ul>
        {% for subject in subjects %}

        <li>
            <a href="/temas/{{ subject.pk }}/">
                {{ subject.name }}
            </a>
        </li>

        {% endfor %}

    </ul>

</div>


{% endblock content %}

taskmaster/tasks/templates/tasks/list_tasks.html
{% extends 'tasks/base.html' %}

{% block content %}

{% include 'tasks/task_table.html' %}



{% endblock content %}

taskmaster/tasks/templates/tasks/navbar.html
{% load static %}
<nav class="navbar" role="navigation" aria-label="main navigation">

    <div class="navbar-brand">

        <a class="navbar-item" href="/">
            <img src="{% static 'tasks/img/logo-64x64.png' %}" width="32" height="32">
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">

            <a class="navbar-item" href="/tareas/">
                Tareas
            </a>

            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                    Por prioridades
                </a>

                <div class="navbar-dropdown">
                    <a class="navbar-item" href="/tareas/h/">
                        Alta
                    </a>
                    <a class="navbar-item" href="/tareas/n/">
                        Normal
                    </a>
                    <a class="navbar-item" href="/tareas/l/">
                        Baja
                    </a>
                    <hr class="navbar-divider">
                    <a class="navbar-item" href="/tareas/alta">
                        Nueva tarea
                    </a>
                </div>
            </div>
        </div>

        <div class="navbar-end">
            <div class="navbar-item">

                <form method="POST" action="/search/">
                    {% csrf_token %}

                    <div class="field has-addons">

                        <div class="control">
                            <input type="search" class="input" placeholder="Texto a buscar" name="query"
                                value="{{ query }}">
                        </div>

                        <div class="control">
                            <button type="submit" class="input" name="ok" value="buscar">

                                <i class="fas fa-search"></i>
                            </button>

                        </div>
                    </div>
                </form>


            </div>
            <div class="navbar-item">
                <a class="button is-primary" href="/admin/">
                    <strong>Admin</strong>
                </a>
            </div>
        </div>
    </div>
</nav>

taskmaster/tasks/templates/tasks/search.html
{% extends 'tasks/base.html' %}

{% block content %}

<form action="/search/" method="POST">
    {% csrf_token %}

    <table class="table">

        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <button type="submit" value="ok">Buscar</button>
            </td>
        </tr>
    </table>


</form>

{% if tasks %}
{% include 'tasks/task_table.html' %}
{% endif %}

{% endblock content %}

taskmaster/tasks/templates/tasks/subject_detail.html
{% extends 'tasks/base.html' %}

{% block content %}
<h2> {{ subject.name }} </h2>

<p>Creado el {{ subject.created }}</p>
<p>Actualizado por última vez el {{ subject.updated }}</p>

<table>
    {% for task in subject.tasks.all %}<tr>
        <td>{{ task.id }}</td>
        <td>{{ task.title }}</td>
    </tr>{% endfor %}
</table>
{% endblock content %}

taskmaster/tasks/templates/tasks/task_table.html
<table class="table is-striped is-hoverable">
    <thead>
        <tr>
            <th>Id. tarea</th>
            <th>Título</th>
            <th>Fecha de entrega</th>
            <th>Urgente</th>
            <th>Prioridad</th>
        </tr>
    </thead>
    <tbody>
        {% for task in tasks %}
        <tr>
            <td>

                <a href="{% url 'edit_task' pk=task.pk %}" role="botton" class="buttom is-primary">
                    {{ task.id }}
                </a>
            </td>
            <td>
                {% if forloop.first %}
                <b> {{ task.title|capfirst|add:" ⚙" }} </b>
                {% else %}
                {{ task.title }}
                {% endif %}
            </td>
            <td>
                {% if task.due_date %}
                {{ task.due_date }}
                {% endif %}
            </td>
            <td>
                {% if task.urgent %}
                <b class="urgente"> Si </b>
                {% else %}
                <i class="no-urgente"> No </i>
                {% endif %}
            </td>
            <td>
                {{ task.get_priority_display }}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>